language: erlang
dist: trusty

script:
   - make
   - make test
   - ./rebar3 coveralls send

otp_release:
   - 20.1
   - 20.0
   - 19.2
   - 18.3

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f8c131737ec5d25fe9a
    on_success: change
    on_failure: always
    on_start: never


